events/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from grandrapidsafterhours import settings

app_name = 'events'
urlpatterns = [
    url(r'^user/(?P<username>[-\w]+)/$', 'events.views.event_users',
        name='events_event_user'),
    url(r'^$', 'events.views.event_index', name="event_index" ),
    url(r'^event_list/$', 'events.views.event_index', name='event_list'),
    url(r'event_manager/$', 'events.views.event_manager', name='event_manager'),
    url(r'event_manager/event_form/$', 'events.views.event_form', name='event_form'),
    url(r'signup', 'events.views.signup', name='signup'),
    url(r'^weeklybeat/$', 'events.views.weeklybeat', name='weeklybeat'),
    url(r'^weekendbeat/$', 'events.views.weekendbeat', name='weekendbeat'),
    url(r'/delete_event/$', 'events.views.deleteEvent', name='deleteEvent'),
    url(r'subscribe', 'events.views.subscribe', name='subscribe'),
]
if settings.DEBUG:
  urlpatterns.append(url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 
        'document_root': settings.MEDIA_ROOT,
      }),)

grandrapidsafterhours/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from events import views


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'', include('events.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {
            'template_name': 'login.html'
        },
        name='grah_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {
         'next_page': reverse_lazy('events:event_index')
       },
      name='grah_logout'),
    url(r'^events/signup',  'events.views.signup', name='signup'),

]


# urlpatterns = patterns('',
#                        (r'^admin/', admin.site.urls),
#                        (r'^', include('events.urls')),
#                        ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
{% load svg %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>

</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->


<!-- Video for the backgorund- -->
 <video id="bgvid" autoplay loop style="width: 100%" class="hidden-sm hidden-xs">
    <source preload="auto" src="{% static 'video/guitarSolobg.webm' %}" type="video/webm" poster="{% static 'img/GrandRapidsSkyline_night2009.jpg' %}">
 </video>

<div class="container">
    {% block mainnavbar %}{% endblock mainnavbar %}
</div>
<div class="container-fluid" id="mainEventContainer"> <!-- div for content block -->
    {% block content %}{% endblock %}
</div> <!-- end div for content block -->


<!-- /container -->
    <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.11.2.min.js"%}"><\/script>')</script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','UA-XXXXX-X','auto');ga('send','pageview');
    </script>
    <footer >
        <div id="footerContainer">
            <div id="copyrightsDiv">

            </div>
            <div class="clearDiv"></div>
            <div id="socialMediaDiv">
                <div id="facebook">
                   <a href="https://www.facebook.com/GRAfterHrs/">{% svg '_facebook_icon' %}</a>
                </div>
            </div>
        </div>
  </footer>
</body>

</html>

templates/base_editors.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>

        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui-timepicker-addon.css' %}">
        <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/jquery-ui.js' %}"></script>
        <script src="{% static 'js/jquery-ui-timepicker-addon.js' %}"></script>
        <script src="{% static 'js/mainEditor.js' %}"></script>
        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        {{ form.media }}

    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <nav id="nav_bar2" class="navbar navbar-inverse" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button"  class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
                <h1>Event Manager</h1>
            </div>
            <div id="navbar" class="navbar-collapse collapse">

            </div><!--/.navbar-collapse -->
          </div>
        </nav>
    <div class="container">
        <div>
            {% block content %}{% endblock %}
        </div>
      <hr>

    </div> <!-- /container -->
        <script>window.jQuery || document.write('<script src="{% static "js/vendor/jquery-1.11.2.min.js"%}"><\/script>')</script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>

    </body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block mainnavbar %}
    {% include 'mainnavbar.html' %}
{% endblock mainnavbar %}
{% block title %}Login{% endblock %}
{% block toggle_login %}{% endblock %}


{% block heading %}
<h2>login</h2>
{% endblock %}
{% block content %}
  <form action="{% url 'grah_login' %}" method="post" accept-charset="utf-8">
     {{ form|crispy }}
     {% csrf_token %}
     <input type="hidden" name="next" value="{{ next }}">
     <input class="btn btn-default" type="submit" value="login">
  </form>
{% endblock %}

templates/mainnavbar.html
{% load staticfiles %}
      <nav id="nav_bar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div id="headerImageDiv">
                <a class="navbar-brand" href="#">
                  <video id="Logo_animated"   autoplay preload="auto" loop >
                    <source src="{% static 'video/grah_logoanim04.webm' %}" type="video/mp4">
                  </video>
                </a>
            </div>
           <!-- <div >
                <a class="navbar-brand" href="#"><img id="grahlogo" class="img-responsive" src="{% static 'img/grahlogo.png' %}" alt="Grand Rapids After Hours" /></a>
            </div> -->
          <div  class="navbar-collapse collapse">
            {% if currentPage == "/events/signup.html" %}
              <a href="/" class="btn btn-danger pull-right" id="btnCancelSignup">Cancel</a>          
            {% else %}
              {% block toggle_login %}
                 {% include "toggle_login.html" %}
              {% endblock %}
            {% endif %}
          </div><!-- navbar-collapse -->
        </div>
      </nav>

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Sign Up
{% endblock title %}

{% block mainnavbar %}
    {% include 'mainnavbar.html' %}
{% endblock mainnavbar %}   

{% block content %} 
    <div id="signup-container">
        <div class="col-lg-3">
        </div>
          
        <div id="signup-form" class="col-lg-6">
            <form class='' method="post" action='events/signup.html'>
                {% csrf_token %}
                Please fill in the following information:&nbsp;<span class="text-red">*</span>&nbsp;= required information
                <label for="username">User Name:</label><span class="text-red">*</span>
                <input type="text" class="form-control" name="username" placeholder="User Name" value=""/>
                
                <label for="firstname">Firstname:</label> 
                <input type="text" class="form-control" name="firstname" placeholder="First Name" value=""/> 
                <label for="lastname">Lastname:</label> 
                <input type="text" class="form-control" name="lastname" placeholder="Last Name" value=""/> 

                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" placeholder="Email" value=""/>
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password" placeholder="Password" value=""/>
                <label for="password_confirmation">Password Confirmation:</label>
                <input type="password" class="form-control" name="password_confirmation" placeholder="Password Confirmation"/>
                <input type="checkbox" id="cbNewsletter" name="newsletter"/> 
                <span id="spanAddNewsletter">
                    Yes, I want Grand Rapids After Hours Newsletter emailed to me.
                </span>
                <button type='submit' class='btn btn-primary'>Sign me up</button>
            </form>
        </div>
    </div>
<script type="text/javascript">
    $("#nav_bar").css({ "top": 0, "background-color": "#000" });
</script>
{% endblock content %}

templates/toggle_login.html
{% if user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                <span id="username">{{ user.first_name }}</span><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                {% if isAdmin %}
                    <li><a href="/admin/">Admin</a> </li>
                {% endif %}
                {% if isEventManager %}
                    <li><a href="{% url 'events:event_manager' %}">Event Manager</a> </li>
                {% endif %}
                <li><a href="{% url 'grah_logout' %}">Logout</a> </li>
            </ul>
        </li>
    </ul>
{% else %}

    <form class="navbar-form navbar-right" role="form" action="{% url 'grah_login' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
        <div class="form-group frontPageLogin">
            <input type="text" placeholder="Username" class="form-control" name="username">
        </div>
        <div class="form-group frontPageLogin">
            <input type="password" placeholder="Password" class="form-control" name="password">
        </div>
        <button type="submit" class="btn btn-success" id="btnLoginSubmit">Sign in</button>
        <div class="form-group">
            <a href="{% url 'events:signup' %}" id="btnJoin" class="btn btn-primary frontPageLoginJoin">Join</a>
        </div>
    </form>


{% endif %}

templates/weeklybeat_base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}" >
    <link type="text/css" rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/weeklybeat.css' %}" >
    <script type="text/javascript" src="{% static 'js/vendor/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/jquery-ui.min.js' %}"></script>
    <title>Weekly Beat </title>
</head>
<body>
<div id="headDiv">
    <div id="titleDiv">
       <a href="http://108.175.10.157">
           <img class="img-responsive" id="grahlogo" src="{% static 'img/grahlogo.png' %}" />
       </a>
        <h3 class="h3Title">YOUR GUIDE TO AFTER HOURS</h3>
        <h3 class="h3Title">GRAND RAPIDS EVENTS</h3>
    </div>
</div>
{% block content %}{% endblock %}
</body>
<footer>
    <div id="footerDiv">

    </div>
</footer>
</html>